version: '3.5'

services:
  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: elasticsearch
    environment:
      - ELASTIC_PASSWORD=3l4s71c
      - discovery.type=single-node
    healthcheck:
      test: ['CMD', 'nc', '-zv', 'elasticsearch', '9200']
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: elasticsearch
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 9200:9200
    restart: always
    deploy:
      resources:
        limits:
          memory: 1GB

  baseline:
    image: provide/baseline
    entrypoint: ./ops/run_api.sh
    container_name: bpi-api
    depends_on:
      - elasticsearch
    environment:
      - BASELINE_ORGANIZATION_ADDRESS=
      - BASELINE_REGISTRY_CONTRACT_ADDRESS=
      - DATABASE_HOST=host.docker.internal
      - DATABASE_NAME=baseline_dev
      - DATABASE_USER=baseline
      - DATABASE_PASSWORD=baseline
      - IDENT_API_HOST=host.docker.internal:8081
      - IDENT_API_SCHEME=http
      - LOG_LEVEL=DEBUG
      - NATS_CLIENT_PREFIX=baseline
      - NATS_URL=nats://host.docker.internal:4222
      - NATS_JETSTREAM_URL=nats://host.docker.internal:4222
      - NCHAIN_API_HOST=host.docker.internal:8085
      - NCHAIN_API_SCHEME=http
      - NCHAIN_BASELINE_NETWORK_ID=
      - PRIVACY_API_HOST=host.docker.internal:8083
      - PRIVACY_API_SCHEME=http
      - PROVIDE_ORGANIZATION_ID=
      - PROVIDE_ORGANIZATION_REFRESH_TOKEN=
      - BASELINE_WORKGROUP_ID=
      - PROVIDE_SOR_IDENTIFIER=ephemeral
      - PROVIDE_SOR_URL=
      - REDIS_HOSTS=host.docker.internal:6379
      - VAULT_API_HOST=host.docker.internal:8082
      - VAULT_API_SCHEME=http
      - VAULT_REFRESH_TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6IjEwOjJlOmQ5OmUxOmI4OmEyOjM0OjM3Ojk5OjNhOjI0OmZjOmFhOmQxOmM4OjU5IiwidHlwIjoiSldUIn0.eyJhdWQiOiJodHRwczovL3Byb3ZpZGUuc2VydmljZXMvYXBpL3YxIiwiaWF0IjoxNjA1NzkxMjQ4LCJpc3MiOiJodHRwczovL2lkZW50LnByb3ZpZGUuc2VydmljZXMiLCJqdGkiOiI5YjUxNGIxNS01NTdlLTRhYWQtYTcwOC0wMTcwZTAwZWE1ZmIiLCJuYXRzIjp7InBlcm1pc3Npb25zIjp7InN1YnNjcmliZSI6eyJhbGxvdyI6WyJhcHBsaWNhdGlvbi4zNjAxNTdmOC1kNWExLTQ0NDAtOTE4Yi1mNjhiYjM5YzBkODAiLCJ1c2VyLjIzY2MwN2UwLTM4NTEtNDBkZC1iNjc1LWRmNzY4MDY3MmY3ZCIsIm5ldHdvcmsuKi5jb25uZWN0b3IuKiIsIm5ldHdvcmsuKi5zdGF0dXMiLCJwbGF0Zm9ybS5cdTAwM2UiXX19fSwicHJ2ZCI6eyJhcHBsaWNhdGlvbl9pZCI6IjM2MDE1N2Y4LWQ1YTEtNDQ0MC05MThiLWY2OGJiMzljMGQ4MCIsImV4dGVuZGVkIjp7InBlcm1pc3Npb25zIjp7IioiOjUxMH19LCJwZXJtaXNzaW9ucyI6NTEwLCJ1c2VyX2lkIjoiMjNjYzA3ZTAtMzg1MS00MGRkLWI2NzUtZGY3NjgwNjcyZjdkIn0sInN1YiI6ImFwcGxpY2F0aW9uOjM2MDE1N2Y4LWQ1YTEtNDQ0MC05MThiLWY2OGJiMzljMGQ4MCJ9.SUh84MKBNstdu3KFu1zEAQq03xbPw1D0lLXeogz1HfBJy77bIGf7HLvCuc6bjkh0xj3cEuEus1dC1Dj3BvlZoSXsvz_biTzSapkXzJjpkwOL6qkYDmqTPZvXwqmk-mUNrHTPkqdiIJL7xA46tzHW3E_hjSA9HjEk1kXjPdJQ6_ifkgWNoAaSD--kudIrhZ7vLnfy0H1JEAOsXzSAMoc5_pNG2n79m0ywvb_4l9BqdsHW8N3xSQOFjcp9gD_tqo6ffug3pkpoy-RSguM_OaMR2lj_CHhYxAt0phtjUceDD3K1h5iZ38kSl7izhOdULMmGBhVpBMoSy6_R6ZzpCL3pj8FcReX9RXR5oYpm8PDtlmWqblQzjwY00-uYLfOX0_iS4MGfEsjadZPfTmJLcOTYC7H4PL9ZRu_XtMDUrGBQQz5b_ad2ZzMXbBNeU6vbxVKDG8VFKWOHAemqHTcvuOAsOCLIqOu-eJpZHlXbx-FXPTYledd-GBDe7IjaC9ll_JK3utCOnCq0qUs6lnXIrQ_Sp1LcTKJJ7aY5f9TxeoAuL-ghDbQ3Xkw6huKyPCz2evOwVLwrB9ZRMlQXgmTnB1OeQvWii1WbmkyV1Zhbz_RPB8ckK7_mFxuPvsXK8wTFiWFmj96sRX470kV-ooSfM5CzKZhSLqgyyaUNC0VaCPq0uuE
      - BASELINE_ORGANIZATION_MESSAGING_ENDPOINT=nats://host.docker.internal:4221
      - BASELINE_ORGANIZATION_PROXY_ENDPOINT=http://baseline:8080
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - ELASTICSEARCH_ACCEPT_SELF_SIGNED_CERTIFICATE=false
      - ELASTICSEARCH_API_SCHEME=http
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=3l4s71c
      - SERVICENOW_LIST_SCHEMAS_API_PATH=setup_configuration/ListSchemas
      - SERVICENOW_SCHEMA_DETAILS_API_PATH=setup_configuration/GetSchemaDetails
      - SERVICENOW_HEALTHCHECK_API_PATH=api/now/branding
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://baseline:8080/status']
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: bpi-api
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 8086:8080
    restart: always

  baseline-consumer:
    image: provide/baseline
    entrypoint: ./ops/run_consumer.sh
    container_name: bpi-consumer
    depends_on:
      - elasticsearch
    environment:
      - BASELINE_ORGANIZATION_ADDRESS=
      - BASELINE_REGISTRY_CONTRACT_ADDRESS=
      - DATABASE_HOST=host.docker.internal
      - DATABASE_NAME=baseline_dev
      - DATABASE_USER=baseline
      - DATABASE_PASSWORD=baseline
      - IDENT_API_HOST=host.docker.internal:8081
      - IDENT_API_SCHEME=http
      - LOG_LEVEL=DEBUG
      - NATS_CLIENT_PREFIX=baseline
      - NATS_URL=nats://host.docker.internal:4222
      - NATS_JETSTREAM_URL=nats://host.docker.internal:4222
      - NCHAIN_API_HOST=host.docker.internal:8085
      - NCHAIN_API_SCHEME=http
      - NCHAIN_BASELINE_NETWORK_ID=
      - PRIVACY_API_HOST=host.docker.internal:8083
      - PRIVACY_API_SCHEME=http
      - PROVIDE_ORGANIZATION_ID=
      - PROVIDE_ORGANIZATION_REFRESH_TOKEN=
      - BASELINE_WORKGROUP_ID=
      - PROVIDE_SOR_IDENTIFIER=ephemeral
      - PROVIDE_SOR_URL=
      - REDIS_HOSTS=host.docker.internal:6379
      - VAULT_API_HOST=host.docker.internal:8082
      - VAULT_API_SCHEME=http
      - VAULT_REFRESH_TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6IjEwOjJlOmQ5OmUxOmI4OmEyOjM0OjM3Ojk5OjNhOjI0OmZjOmFhOmQxOmM4OjU5IiwidHlwIjoiSldUIn0.eyJhdWQiOiJodHRwczovL3Byb3ZpZGUuc2VydmljZXMvYXBpL3YxIiwiaWF0IjoxNjA1NzkxMjQ4LCJpc3MiOiJodHRwczovL2lkZW50LnByb3ZpZGUuc2VydmljZXMiLCJqdGkiOiI5YjUxNGIxNS01NTdlLTRhYWQtYTcwOC0wMTcwZTAwZWE1ZmIiLCJuYXRzIjp7InBlcm1pc3Npb25zIjp7InN1YnNjcmliZSI6eyJhbGxvdyI6WyJhcHBsaWNhdGlvbi4zNjAxNTdmOC1kNWExLTQ0NDAtOTE4Yi1mNjhiYjM5YzBkODAiLCJ1c2VyLjIzY2MwN2UwLTM4NTEtNDBkZC1iNjc1LWRmNzY4MDY3MmY3ZCIsIm5ldHdvcmsuKi5jb25uZWN0b3IuKiIsIm5ldHdvcmsuKi5zdGF0dXMiLCJwbGF0Zm9ybS5cdTAwM2UiXX19fSwicHJ2ZCI6eyJhcHBsaWNhdGlvbl9pZCI6IjM2MDE1N2Y4LWQ1YTEtNDQ0MC05MThiLWY2OGJiMzljMGQ4MCIsImV4dGVuZGVkIjp7InBlcm1pc3Npb25zIjp7IioiOjUxMH19LCJwZXJtaXNzaW9ucyI6NTEwLCJ1c2VyX2lkIjoiMjNjYzA3ZTAtMzg1MS00MGRkLWI2NzUtZGY3NjgwNjcyZjdkIn0sInN1YiI6ImFwcGxpY2F0aW9uOjM2MDE1N2Y4LWQ1YTEtNDQ0MC05MThiLWY2OGJiMzljMGQ4MCJ9.SUh84MKBNstdu3KFu1zEAQq03xbPw1D0lLXeogz1HfBJy77bIGf7HLvCuc6bjkh0xj3cEuEus1dC1Dj3BvlZoSXsvz_biTzSapkXzJjpkwOL6qkYDmqTPZvXwqmk-mUNrHTPkqdiIJL7xA46tzHW3E_hjSA9HjEk1kXjPdJQ6_ifkgWNoAaSD--kudIrhZ7vLnfy0H1JEAOsXzSAMoc5_pNG2n79m0ywvb_4l9BqdsHW8N3xSQOFjcp9gD_tqo6ffug3pkpoy-RSguM_OaMR2lj_CHhYxAt0phtjUceDD3K1h5iZ38kSl7izhOdULMmGBhVpBMoSy6_R6ZzpCL3pj8FcReX9RXR5oYpm8PDtlmWqblQzjwY00-uYLfOX0_iS4MGfEsjadZPfTmJLcOTYC7H4PL9ZRu_XtMDUrGBQQz5b_ad2ZzMXbBNeU6vbxVKDG8VFKWOHAemqHTcvuOAsOCLIqOu-eJpZHlXbx-FXPTYledd-GBDe7IjaC9ll_JK3utCOnCq0qUs6lnXIrQ_Sp1LcTKJJ7aY5f9TxeoAuL-ghDbQ3Xkw6huKyPCz2evOwVLwrB9ZRMlQXgmTnB1OeQvWii1WbmkyV1Zhbz_RPB8ckK7_mFxuPvsXK8wTFiWFmj96sRX470kV-ooSfM5CzKZhSLqgyyaUNC0VaCPq0uuE
      - BASELINE_ORGANIZATION_MESSAGING_ENDPOINT=nats://host.docker.internal:4221
      - BASELINE_ORGANIZATION_PROXY_ENDPOINT=http://baseline:8080
      - BASELINE_API_SCHEME=http
      - BASELINE_API_HOST=baseline:8080
      - BASELINE_API_PATH=api/v1
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - ELASTICSEARCH_ACCEPT_SELF_SIGNED_CERTIFICATE=false
      - ELASTICSEARCH_API_SCHEME=http
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=3l4s71c
      - SERVICENOW_LIST_SCHEMAS_API_PATH=setup_configuration/ListSchemas
      - SERVICENOW_SCHEMA_DETAILS_API_PATH=setup_configuration/GetSchemaDetails
      - SERVICENOW_HEALTHCHECK_API_PATH=api/now/branding
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://baseline:8080/status']
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: bpi-consumer
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
