version: '3.5'

services:
  tenant-postgres:
    image: postgres
    container_name: postgres-tenant
    environment:
      - POSTGRES_DB=prvd
      - POSTGRES_USER=prvd
      - POSTGRES_PASSWORD=prvdp455
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'prvd', '-d', 'prvd']
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: tenant-postgres
    volumes:
      - tenant-axiom-db:/var/lib/postgresql/data
    networks:
      - tenant-axiom
    ports:
      - 5434:5432
    restart: always

  tenant-redis:
    image: redis
    container_name: redis-tenant
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: tenant-redis
    networks:
      - tenant-axiom
    ports:
      - 6381:6379
    restart: always

  tenant-nats:
    image: provide/nats-server:2.5.0-PRVD
    container_name: nats-tenant
    command:
      [
        '--js',
        '--server_name',
        'tenant-nats1',
        '-auth',
        'testtoken',
        '-p',
        '4226',
        '-D',
        '-V',
      ]
    environment:
      JWT_SIGNER_PUBLIC_KEY: |-
        -----BEGIN PUBLIC KEY-----
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAullT/WoZnxecxKwQFlwE
        9lpQrekSD+txCgtb9T3JvvX/YkZTYkerf0rssQtrwkBlDQtm2cB5mHlRt4lRDKQy
        EA2qNJGM1Yu379abVObQ9ZXI2q7jTBZzL/Yl9AgUKlDIAXYFVfJ8XWVTi0l32Vsx
        tJSd97hiRXO+RqQu5UEr3jJ5tL73iNLp5BitRBwa4KbDCbicWKfSH5hK5DM75EyM
        R/SzR3oCLPFNLs+fyc7zH98S1atglbelkZsMk/mSIKJJl1fZFVCUxA+8CaPiKbpD
        QLpzydqyrk/y275aSU/tFHidoewvtWorNyFWRnefoWOsJFlfq1crgMu2YHTMBVtU
        SJ+4MS5D9fuk0queOqsVUgT7BVRSFHgDH7IpBZ8s9WRrpE6XOE+feTUyyWMjkVgn
        gLm5RSbHpB8Wt/Wssy3VMPV3T5uojPvX+ITmf1utz0y41gU+iZ/YFKeNN8WysLxX
        AP3Bbgo+zNLfpcrH1Y27WGBWPtHtzqiafhdfX6LQ3/zXXlNuruagjUohXaMltH+S
        K8zK4j7n+BYl+7y1dzOQw4CadsDi5whgNcg2QUxuTlW+TQ5VBvdUl9wpTSygD88H
        xH2b0OBcVjYsgRnQ9OZpQ+kIPaFhaWChnfEArCmhrOEgOnhfkr6YGDHFenfT3/RA
        PUl1cxrvY7BHh4obNa6Bf8ECAwEAAQ==
        -----END PUBLIC KEY-----
    healthcheck:
      test: ['CMD', '/usr/local/bin/await_tcp.sh', 'localhost:4226']
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: tenant-nats
    networks:
      - tenant-axiom
    ports:
      - 4225:4225
      - 4226:4226
    restart: always
    volumes:
      - ./ops/await_tcp.sh:/usr/local/bin/await_tcp.sh:cached

  tenant-axiom:
    build: ../
    entrypoint: ./ops/run_api.sh
    container_name: axiom-tenant-api
    depends_on:
      - tenant-nats
      - tenant-postgres
      - tenant-redis
    environment:
      - AXIOM_ORGANIZATION_ADDRESS=
      - AXIOM_REGISTRY_CONTRACT_ADDRESS=
      - DATABASE_HOST=tenant-postgres
      - DATABASE_NAME=axiom_dev
      - DATABASE_USER=axiom
      - DATABASE_PASSWORD=axiom
      - IDENT_API_HOST=host.docker.internal:8081
      - IDENT_API_SCHEME=http
      - LOG_LEVEL=DEBUG
      - NATS_CLIENT_PREFIX=axiom
      - NATS_URL=nats://tenant-nats:4226
      - NATS_JETSTREAM_URL=nats://tenant-nats:4226
      - NCHAIN_API_HOST=host.docker.internal:8084
      - NCHAIN_API_SCHEME=http
      - NCHAIN_AXIOM_NETWORK_ID=
      - PRIVACY_API_HOST=host.docker.internal:8083
      - PRIVACY_API_SCHEME=http
      - PROVIDE_ORGANIZATION_ID=
      - PROVIDE_ORGANIZATION_REFRESH_TOKEN=
      - AXIOM_WORKGROUP_ID=
      - PROVIDE_SOR_IDENTIFIER=ephemeral
      - PROVIDE_SOR_URL=
      - REDIS_HOSTS=tenant-redis:6379
      - VAULT_API_HOST=host.docker.internal:8082
      - VAULT_API_SCHEME=http
      - VAULT_REFRESH_TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6IjEwOjJlOmQ5OmUxOmI4OmEyOjM0OjM3Ojk5OjNhOjI0OmZjOmFhOmQxOmM4OjU5IiwidHlwIjoiSldUIn0.eyJhdWQiOiJodHRwczovL3Byb3ZpZGUuc2VydmljZXMvYXBpL3YxIiwiaWF0IjoxNjA1NzkxMjQ4LCJpc3MiOiJodHRwczovL2lkZW50LnByb3ZpZGUuc2VydmljZXMiLCJqdGkiOiI5YjUxNGIxNS01NTdlLTRhYWQtYTcwOC0wMTcwZTAwZWE1ZmIiLCJuYXRzIjp7InBlcm1pc3Npb25zIjp7InN1YnNjcmliZSI6eyJhbGxvdyI6WyJhcHBsaWNhdGlvbi4zNjAxNTdmOC1kNWExLTQ0NDAtOTE4Yi1mNjhiYjM5YzBkODAiLCJ1c2VyLjIzY2MwN2UwLTM4NTEtNDBkZC1iNjc1LWRmNzY4MDY3MmY3ZCIsIm5ldHdvcmsuKi5jb25uZWN0b3IuKiIsIm5ldHdvcmsuKi5zdGF0dXMiLCJwbGF0Zm9ybS5cdTAwM2UiXX19fSwicHJ2ZCI6eyJhcHBsaWNhdGlvbl9pZCI6IjM2MDE1N2Y4LWQ1YTEtNDQ0MC05MThiLWY2OGJiMzljMGQ4MCIsImV4dGVuZGVkIjp7InBlcm1pc3Npb25zIjp7IioiOjUxMH19LCJwZXJtaXNzaW9ucyI6NTEwLCJ1c2VyX2lkIjoiMjNjYzA3ZTAtMzg1MS00MGRkLWI2NzUtZGY3NjgwNjcyZjdkIn0sInN1YiI6ImFwcGxpY2F0aW9uOjM2MDE1N2Y4LWQ1YTEtNDQ0MC05MThiLWY2OGJiMzljMGQ4MCJ9.SUh84MKBNstdu3KFu1zEAQq03xbPw1D0lLXeogz1HfBJy77bIGf7HLvCuc6bjkh0xj3cEuEus1dC1Dj3BvlZoSXsvz_biTzSapkXzJjpkwOL6qkYDmqTPZvXwqmk-mUNrHTPkqdiIJL7xA46tzHW3E_hjSA9HjEk1kXjPdJQ6_ifkgWNoAaSD--kudIrhZ7vLnfy0H1JEAOsXzSAMoc5_pNG2n79m0ywvb_4l9BqdsHW8N3xSQOFjcp9gD_tqo6ffug3pkpoy-RSguM_OaMR2lj_CHhYxAt0phtjUceDD3K1h5iZ38kSl7izhOdULMmGBhVpBMoSy6_R6ZzpCL3pj8FcReX9RXR5oYpm8PDtlmWqblQzjwY00-uYLfOX0_iS4MGfEsjadZPfTmJLcOTYC7H4PL9ZRu_XtMDUrGBQQz5b_ad2ZzMXbBNeU6vbxVKDG8VFKWOHAemqHTcvuOAsOCLIqOu-eJpZHlXbx-FXPTYledd-GBDe7IjaC9ll_JK3utCOnCq0qUs6lnXIrQ_Sp1LcTKJJ7aY5f9TxeoAuL-ghDbQ3Xkw6huKyPCz2evOwVLwrB9ZRMlQXgmTnB1OeQvWii1WbmkyV1Zhbz_RPB8ckK7_mFxuPvsXK8wTFiWFmj96sRX470kV-ooSfM5CzKZhSLqgyyaUNC0VaCPq0uuE
      - AXIOM_ORGANIZATION_MESSAGING_ENDPOINT=nats://tenant-nats:4225
      - AXIOM_ORGANIZATION_API_ENDPOINT=http://tenant-axiom:8080
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://tenant-axiom:8080/status']
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: tenant-axiom
    networks:
      - tenant-axiom
    ports:
      - 8086:8080
    restart: always

  tenant-axiom-consumer:
    build: ../
    entrypoint: ./ops/run_consumer.sh
    container_name: axiom-tenant-consumer
    depends_on:
      - tenant-nats
      - tenant-postgres
      - tenant-redis
    environment:
      - AXIOM_ORGANIZATION_ADDRESS=
      - AXIOM_REGISTRY_CONTRACT_ADDRESS=
      - DATABASE_HOST=tenant-postgres
      - DATABASE_NAME=axiom_dev
      - DATABASE_USER=axiom
      - DATABASE_PASSWORD=axiom
      - IDENT_API_HOST=host.docker.internal:8081
      - IDENT_API_SCHEME=http
      - LOG_LEVEL=DEBUG
      - NATS_CLIENT_PREFIX=axiom
      - NATS_URL=nats://tenant-nats:4226
      - NATS_JETSTREAM_URL=nats://tenant-nats:4226
      - NCHAIN_API_HOST=host.docker.internal:8084
      - NCHAIN_API_SCHEME=http
      - NCHAIN_AXIOM_NETWORK_ID=
      - PRIVACY_API_HOST=host.docker.internal:8083
      - PRIVACY_API_SCHEME=http
      - PROVIDE_ORGANIZATION_ID=
      - PROVIDE_ORGANIZATION_REFRESH_TOKEN=
      - AXIOM_WORKGROUP_ID=
      - PROVIDE_SOR_IDENTIFIER=ephemeral
      - PROVIDE_SOR_URL=
      - REDIS_HOSTS=tenant-redis:6379
      - VAULT_API_HOST=host.docker.internal:8082
      - VAULT_API_SCHEME=http
      - VAULT_REFRESH_TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6IjEwOjJlOmQ5OmUxOmI4OmEyOjM0OjM3Ojk5OjNhOjI0OmZjOmFhOmQxOmM4OjU5IiwidHlwIjoiSldUIn0.eyJhdWQiOiJodHRwczovL3Byb3ZpZGUuc2VydmljZXMvYXBpL3YxIiwiaWF0IjoxNjA1NzkxMjQ4LCJpc3MiOiJodHRwczovL2lkZW50LnByb3ZpZGUuc2VydmljZXMiLCJqdGkiOiI5YjUxNGIxNS01NTdlLTRhYWQtYTcwOC0wMTcwZTAwZWE1ZmIiLCJuYXRzIjp7InBlcm1pc3Npb25zIjp7InN1YnNjcmliZSI6eyJhbGxvdyI6WyJhcHBsaWNhdGlvbi4zNjAxNTdmOC1kNWExLTQ0NDAtOTE4Yi1mNjhiYjM5YzBkODAiLCJ1c2VyLjIzY2MwN2UwLTM4NTEtNDBkZC1iNjc1LWRmNzY4MDY3MmY3ZCIsIm5ldHdvcmsuKi5jb25uZWN0b3IuKiIsIm5ldHdvcmsuKi5zdGF0dXMiLCJwbGF0Zm9ybS5cdTAwM2UiXX19fSwicHJ2ZCI6eyJhcHBsaWNhdGlvbl9pZCI6IjM2MDE1N2Y4LWQ1YTEtNDQ0MC05MThiLWY2OGJiMzljMGQ4MCIsImV4dGVuZGVkIjp7InBlcm1pc3Npb25zIjp7IioiOjUxMH19LCJwZXJtaXNzaW9ucyI6NTEwLCJ1c2VyX2lkIjoiMjNjYzA3ZTAtMzg1MS00MGRkLWI2NzUtZGY3NjgwNjcyZjdkIn0sInN1YiI6ImFwcGxpY2F0aW9uOjM2MDE1N2Y4LWQ1YTEtNDQ0MC05MThiLWY2OGJiMzljMGQ4MCJ9.SUh84MKBNstdu3KFu1zEAQq03xbPw1D0lLXeogz1HfBJy77bIGf7HLvCuc6bjkh0xj3cEuEus1dC1Dj3BvlZoSXsvz_biTzSapkXzJjpkwOL6qkYDmqTPZvXwqmk-mUNrHTPkqdiIJL7xA46tzHW3E_hjSA9HjEk1kXjPdJQ6_ifkgWNoAaSD--kudIrhZ7vLnfy0H1JEAOsXzSAMoc5_pNG2n79m0ywvb_4l9BqdsHW8N3xSQOFjcp9gD_tqo6ffug3pkpoy-RSguM_OaMR2lj_CHhYxAt0phtjUceDD3K1h5iZ38kSl7izhOdULMmGBhVpBMoSy6_R6ZzpCL3pj8FcReX9RXR5oYpm8PDtlmWqblQzjwY00-uYLfOX0_iS4MGfEsjadZPfTmJLcOTYC7H4PL9ZRu_XtMDUrGBQQz5b_ad2ZzMXbBNeU6vbxVKDG8VFKWOHAemqHTcvuOAsOCLIqOu-eJpZHlXbx-FXPTYledd-GBDe7IjaC9ll_JK3utCOnCq0qUs6lnXIrQ_Sp1LcTKJJ7aY5f9TxeoAuL-ghDbQ3Xkw6huKyPCz2evOwVLwrB9ZRMlQXgmTnB1OeQvWii1WbmkyV1Zhbz_RPB8ckK7_mFxuPvsXK8wTFiWFmj96sRX470kV-ooSfM5CzKZhSLqgyyaUNC0VaCPq0uuE
      - AXIOM_ORGANIZATION_MESSAGING_ENDPOINT=nats://tenant-nats:4225
      - AXIOM_ORGANIZATION_API_ENDPOINT=http://tenant-axiom:8080
      - AXIOM_API_SCHEME=http
      - AXIOM_API_HOST=tenant-axiom:8080
      - AXIOM_API_PATH=api/v1
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://tenant-axiom:8080/status']
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: tenant-axiom-consumer
    networks:
      - tenant-axiom
    restart: always

networks:
  tenant-axiom:
    driver: bridge
volumes:
  tenant-axiom-db:
