name: Axiom (dev)
on:
  push:
    branches:
      - dev
jobs:
  push_to_branch:
    runs-on: ubuntu-latest
    timeout-minutes: 10    
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.INTEGRATION_SLACK_WEBHOOK }}
    steps:
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Checkout ident
        uses: actions/checkout@v2
        with:
          repository: provideplatform/ident
          path: 'ident'
          ref: dev
          token: ${{ secrets.DEPLOY_GITHUB_PAT }}             
      - name: Checkout axiom
        uses: actions/checkout@v2
        with:
          path: 'axiom'
      - run: docker-compose -f ./ops/docker-compose.yml build --no-cache axiom-api
        working-directory: axiom
      - run: docker-compose -f ./ops/docker-compose.yml up -d
        working-directory: axiom
      - run: TAGS=integration ./ops/run_local_tests_long.sh
        working-directory: axiom
      - run: docker-compose -f ./ops/docker-compose.yml logs
        working-directory: axiom
      - run: docker-compose -f ./ops/docker-compose.yml down
        working-directory: axiom
      - run: docker volume rm ops_prvd-db
        working-directory: axiom   
      - name: Push Docker Image
        if: success()
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
          repository: provide/axiom
          tags: dev
          path: 'axiom'
      - name: Send Slack Notification
        if: failure()  
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
