name: Baseline
on: 
  push:
    branches:
      - master
jobs:
  push_to_branch:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.INTEGRATION_SLACK_WEBHOOK }}
    steps:
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
      - name: Checkout ident
        uses: actions/checkout@v2
        with:
          repository: provideapp/ident
          path: 'ident'
          ref: master
          token: ${{ secrets.DEPLOY_GITHUB_PAT }}
      - name: Checkout baseline
        uses: actions/checkout@v2
        with:
          path: 'baseline'
      - run: docker-compose -f ./ops/docker-compose.yml build --no-cache baseline-proxy
        working-directory: baseline
      - run: docker-compose -f ./ops/docker-compose.yml up -d
        working-directory: baseline
      - run: TAGS=integration ./ops/run_local_tests_long.sh
        working-directory: baseline
      - run: docker-compose -f ./ops/docker-compose.yml logs
        working-directory: baseline
      - run: docker-compose -f ./ops/docker-compose.yml down
        working-directory: baseline
      - run: docker volume rm ops_prvd-db
        working-directory: baseline
      - name: Push Docker Image
        if: success()
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
          repository: provide/baseline
          tags: "latest"
          path: 'baseline'
      - name: Send Slack Notification
        if: failure()  
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
